# Generated by Django 5.2 on 2025-04-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Team Member', 'Team Member')], default='TEAM_MEMBER', max_length=20),
        ),
    ]
