# Generated by Django 5.2 on 2025-04-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('TEAM_MEMBER', 'Team Member')], default='TEAM_MEMBER', max_length=20),
        ),
    ]
