# Generated by Django 5.2 on 2025-04-24 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "lifecycle_stage",
                    models.IntegerField(
                        choices=[
                            (1, "To Do"),
                            (2, "In Progress"),
                            (3, "Review"),
                            (4, "Completed"),
                        ],
                        default=1,
                        verbose_name="Lifecycle Stage",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Medium"),
                            (3, "High"),
                            (4, "Critical"),
                        ],
                        default=1,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Deadline"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to="tasks.task",
                        verbose_name="Task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned User",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.ManyToManyField(
                related_name="assigned_tasks",
                through="tasks.TaskAssignment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned To",
            ),
        ),
        migrations.CreateModel(
            name="TaskCollaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_collaborations",
                        to="tasks.task",
                        verbose_name="Task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_collaborations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Collaborator",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="collaborators",
            field=models.ManyToManyField(
                related_name="collaborated_tasks",
                through="tasks.TaskCollaborator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Collaborators",
            ),
        ),
    ]
