# Generated by Django 5.2 on 2025-05-06 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_comments",
                to="users.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_user",
                to="users.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tasks",
                to="users.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="taskcollaborator",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_collaborations",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="taskcollaborator",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_collaborations",
                to="users.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="collaborators",
            field=models.ManyToManyField(
                related_name="collaborated_tasks",
                through="tasks.TaskCollaborator",
                to="users.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="taskhistory",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_history",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="taskhistory",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_history",
                to="users.userprofile",
            ),
        ),
    ]
