# Generated by Django 5.2 on 2025-05-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_notification_options_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="mentions",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in_comments", to="users.userprofile"
            ),
        ),
    ]
